//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessBMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int RequestID { get; set; }
        public int SenderPlayerID { get; set; }
        public int ReceiverPlayerID { get; set; }
        public string RequestStatus { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
