//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessBMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LobbyPlayers
    {
        public int LobbyID { get; set; }
        public int PlayerID { get; set; }
        public int GuestID { get; set; }
        public string PlayerStatus { get; set; }
    
        public virtual GameLobby GameLobby { get; set; }
        public virtual GuestPlayers GuestPlayers { get; set; }
        public virtual Player Player { get; set; }
    }
}
