//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessBMC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMCDBEntities : DbContext
    {
        public BMCDBEntities()
            : base("name=BMCDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessages> ChatMessages { get; set; }
        public virtual DbSet<FriendRequest> FriendRequest { get; set; }
        public virtual DbSet<PasswordResetRequests> PasswordResetRequests { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<StatusPlayer> StatusPlayer { get; set; }
        public virtual DbSet<UserScores> UserScores { get; set; }
    }
}
