//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMCWindows.ProfileServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResultOfPlayerDTOQo1Oyztf", Namespace="http://schemas.datacontract.org/2004/07/Service.Results")]
    [System.SerializableAttribute()]
    public partial class OperationResultOfPlayerDTOQo1Oyztf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BMCWindows.ProfileServer.PlayerDTO DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BMCWindows.ProfileServer.PlayerDTO Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorKey {
            get {
                return this.ErrorKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorKeyField, value) != true)) {
                    this.ErrorKeyField = value;
                    this.RaisePropertyChanged("ErrorKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerDTO", Namespace="http://schemas.datacontract.org/2004/07/Service.DTO")]
    [System.SerializableAttribute()]
    public partial class PlayerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((this.PlayerIDField.Equals(value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileServer.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updatePassword", ReplyAction="http://tempuri.org/IProfileService/updatePasswordResponse")]
        BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf updatePassword(string username, string newPassword, string oldPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updatePassword", ReplyAction="http://tempuri.org/IProfileService/updatePasswordResponse")]
        System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf> updatePasswordAsync(string username, string newPassword, string oldPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updateProfilePicture", ReplyAction="http://tempuri.org/IProfileService/updateProfilePictureResponse")]
        BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf updateProfilePicture(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updateProfilePicture", ReplyAction="http://tempuri.org/IProfileService/updateProfilePictureResponse")]
        System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf> updateProfilePictureAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updateEmail", ReplyAction="http://tempuri.org/IProfileService/updateEmailResponse")]
        BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf updateEmail(string email, string confirmationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileService/updateEmail", ReplyAction="http://tempuri.org/IProfileService/updateEmailResponse")]
        System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf> updateEmailAsync(string email, string confirmationCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : BMCWindows.ProfileServer.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<BMCWindows.ProfileServer.IProfileService>, BMCWindows.ProfileServer.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf updatePassword(string username, string newPassword, string oldPassword) {
            return base.Channel.updatePassword(username, newPassword, oldPassword);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf> updatePasswordAsync(string username, string newPassword, string oldPassword) {
            return base.Channel.updatePasswordAsync(username, newPassword, oldPassword);
        }
        
        public BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf updateProfilePicture(string url) {
            return base.Channel.updateProfilePicture(url);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf> updateProfilePictureAsync(string url) {
            return base.Channel.updateProfilePictureAsync(url);
        }
        
        public BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf updateEmail(string email, string confirmationCode) {
            return base.Channel.updateEmail(email, confirmationCode);
        }
        
        public System.Threading.Tasks.Task<BMCWindows.ProfileServer.OperationResultOfPlayerDTOQo1Oyztf> updateEmailAsync(string email, string confirmationCode) {
            return base.Channel.updateEmailAsync(email, confirmationCode);
        }
    }
}
